### ISSUE TITLE
CouchPotato Question

### ISSUE THREAD

**Issue by rv10guy** [xombiemp/ultimate-torrent-setup#43]
In looking at the guide under renaming in CouchPotato, the Move action is being used instead of the link action, however link is used for the Sonarr config. Can you help me understand why?

Thanks!

**Comment by xombiemp** [comment]
In the Sonarr setup when you are configuring the Blackhole download setting Read Only to No tells Sonnar to Move instead of Copy.  So really the Move operation is being used in Sonarr as well as Couchpotato.  The reason we do Move is because the Hardlink is already created by ruTorrent, so we are already dealing with a link that we can just move where it needs to go.
