### ISSUE TITLE
regex for automove match

### ISSUE THREAD

**Issue by ashenkin** [xombiemp/ultimate-torrent-setup#79]
Thanks for this guide - it's awesome, and made setup post-crash very easy.
Two questions: First, why do you use this regex to match labels for automove?
`/^(?!tv\/sonarr$|movie\/radarr$|music\/lidarr$).*$/`
With the negative lookahead, this will match everything but automatically downloaded files.  Don't you want sonarr/radarr/lidarr files to be moved over to the completed directory?
Second, why do a hard link instead of a move from /data/download to /data/complete?  I don't see a good reason to keep a copy in the download directory; just makes things harder to clean up.  And, anticipating a response, yes, i've changed this in my own config.  Just curious about your thinking, as perhaps I've missed something.
Thanks again!!!  Great guide.

**Comment by xombiemp** [comment]
1. I've excluded those labels because I've changed from a blackhole config in Sonarr/Radarr to using the rtorrent integration. So instead of Sonarr looking in the complete folder blindly, it uses the XMLRPC interface to query for when the download is complete and then Sonarr does the hard linking of the file to the final destination directory. I don't want the automove plugin to move those anymore since Sonarr/Radarr are handling it.
2. The hard link is so original in the download directory can continue to seed. I can modify, move or do whatever with the hard link in the complete folder, without worrying about messing up the seeding. The hard link does not consume duplicate space on the filesystem.
